// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/post.proto

package post

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Company              string   `protobuf:"bytes,2,opt,name=company,proto3" json:"company,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

type PostRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content              string   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	User                 *User    `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	GroupId              string   `protobuf:"bytes,4,opt,name=groupId,proto3" json:"groupId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostRequest) Reset()         { *m = PostRequest{} }
func (m *PostRequest) String() string { return proto.CompactTextString(m) }
func (*PostRequest) ProtoMessage()    {}
func (*PostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{1}
}

func (m *PostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostRequest.Unmarshal(m, b)
}
func (m *PostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostRequest.Marshal(b, m, deterministic)
}
func (m *PostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostRequest.Merge(m, src)
}
func (m *PostRequest) XXX_Size() int {
	return xxx_messageInfo_PostRequest.Size(m)
}
func (m *PostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PostRequest proto.InternalMessageInfo

func (m *PostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *PostRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *PostRequest) GetGroupId() string {
	if m != nil {
		return m.GroupId
	}
	return ""
}

type PostResponse struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_44e633a5eb8e0f8a, []int{2}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *PostResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PostResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*PostRequest)(nil), "PostRequest")
	proto.RegisterType((*PostResponse)(nil), "PostResponse")
}

func init() {
	proto.RegisterFile("pb/post.proto", fileDescriptor_44e633a5eb8e0f8a)
}

var fileDescriptor_44e633a5eb8e0f8a = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xdd, 0x75, 0xb7, 0xda, 0x69, 0xeb, 0x21, 0x88, 0xc4, 0x9e, 0xca, 0x9e, 0x0a, 0xc2,
	0x0a, 0xf5, 0x26, 0xde, 0x3c, 0x09, 0x1e, 0x24, 0xe2, 0x03, 0x6c, 0xbb, 0x83, 0x2c, 0xd8, 0x24,
	0xce, 0x4c, 0x04, 0xdf, 0x5e, 0x92, 0x6c, 0x6d, 0x8f, 0xdf, 0x84, 0x3f, 0xdf, 0xfc, 0x03, 0x0b,
	0xbf, 0xbd, 0xf7, 0x8e, 0xa5, 0xf5, 0xe4, 0xc4, 0x35, 0x4f, 0x50, 0x7d, 0x30, 0x92, 0x5a, 0xc2,
	0x65, 0x60, 0x24, 0xdb, 0xed, 0x51, 0x17, 0xab, 0x62, 0x3d, 0x35, 0xff, 0xac, 0x34, 0x5c, 0xec,
	0xdc, 0xde, 0x77, 0xf6, 0x57, 0x97, 0xe9, 0xe9, 0x80, 0x0d, 0xc1, 0xec, 0xcd, 0xb1, 0x18, 0xfc,
	0x0e, 0xc8, 0xa2, 0xae, 0xa1, 0x96, 0x41, 0xbe, 0x0e, 0x3f, 0x64, 0xc8, 0x71, 0x2b, 0x68, 0xe5,
	0x18, 0x4f, 0xa8, 0x6e, 0xa1, 0x8a, 0x12, 0x7d, 0xbe, 0x2a, 0xd6, 0xb3, 0x4d, 0xdd, 0xc6, 0x4d,
	0x4c, 0x1a, 0xc5, 0xd0, 0x27, 0xb9, 0xe0, 0x5f, 0x7a, 0x5d, 0xe5, 0xd0, 0x88, 0xcd, 0x2b, 0xcc,
	0xb3, 0x93, 0xbd, 0xb3, 0x8c, 0xea, 0x06, 0x26, 0x2c, 0x9d, 0x04, 0x4e, 0xd6, 0xda, 0x8c, 0xa4,
	0xae, 0xa0, 0x1c, 0xfa, 0xd1, 0x58, 0x0e, 0x7d, 0x5c, 0x0e, 0x89, 0x5c, 0xb6, 0x4d, 0x4d, 0x86,
	0xcd, 0x63, 0x6e, 0xf0, 0x8e, 0xf4, 0x33, 0xec, 0x50, 0xdd, 0x01, 0x3c, 0x13, 0x76, 0x82, 0x71,
	0xa8, 0xe6, 0xed, 0x49, 0xbb, 0xe5, 0xa2, 0x3d, 0xf5, 0x36, 0x67, 0xdb, 0x49, 0x3a, 0xe1, 0xc3,
	0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4a, 0x4c, 0xad, 0xb6, 0x53, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PostServiceClient is the client API for PostService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostServiceClient interface {
	CreatePost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
}

type postServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPostServiceClient(cc grpc.ClientConnInterface) PostServiceClient {
	return &postServiceClient{cc}
}

func (c *postServiceClient) CreatePost(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, "/PostService/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServiceServer is the server API for PostService service.
type PostServiceServer interface {
	CreatePost(context.Context, *PostRequest) (*PostResponse, error)
}

// UnimplementedPostServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPostServiceServer struct {
}

func (*UnimplementedPostServiceServer) CreatePost(ctx context.Context, req *PostRequest) (*PostResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}

func RegisterPostServiceServer(s *grpc.Server, srv PostServiceServer) {
	s.RegisterService(&_PostService_serviceDesc, srv)
}

func _PostService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PostService/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServiceServer).CreatePost(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PostService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PostService",
	HandlerType: (*PostServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _PostService_CreatePost_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/post.proto",
}
